backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    required: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredblog", widget: "boolean", required: false}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "what-we-do"
    label: "What We Do"
    folder: "src/pages/what-we-do"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "what-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Pretty Title 1", name: "prettytitle1", widget: "string", required: false}
      - {label: "Pretty Title 2", name: "prettytitle2", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", required: false}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "services"
    label: "Services"
    folder: "src/pages/services"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post-services"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Pretty Title 1", name: "prettytitle1", widget: "string", required: false}
      - {label: "Pretty Title 2", name: "prettytitle2", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Service", name: "featuredservice", widget: "boolean", required: false}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post-projects"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Pretty Title 1", name: "prettytitle1", widget: "string", required: false}
      - {label: "Pretty Title 2", name: "prettytitle2", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredprojects", widget: "boolean", required: false}
      - {label: "Home Post", name: "homepost", widget: "boolean", required: false}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "people"
    label: "People"
    folder: "src/pages/people"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "People Key", name: "peoplekey", widget: "hidden", default: "people"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Pretty Title 1", name: "prettytitle1", widget: "string", required: false}
      - {label: "Pretty Title 2", name: "prettytitle2", widget: "string", required: false}
      - {label: "Job Title", name: "jobtitle", widget: "string", required: false}
      - {label: "Job Title 2", name: "jobtitle2", widget: "text", required: false}
      - {label: "Executive Team", name: "executiveteam", widget: "boolean", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Show Titles", name: "showtitles", widget: "boolean", required: false}

  - name: "careers"
    label: "Careers"
    folder: "src/pages/careers"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "career-post"}
      - {label: "Careers Key", name: "careerskey", widget: "hidden", default: "careers"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Pretty Title 1", name: "prettytitle1", widget: "string", required: false}
      - {label: "Pretty Title 2", name: "prettytitle2", widget: "string", required: false}
      - {label: "Featured Career", name: "featuredcareer", widget: "boolean", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Heading 2, name: heading2, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Image Pitch, name: imagepitch, widget: image, required: false}, {label: Link1 Text, name: link1text, widget: text, required: false}, {label: Link1 URL, name: link1url, widget: text, required: false}, {label: Link2 Text, name: link2text, widget: text, required: false}, {label: Link2 URL, name: link2url, widget: text, required: false}]}
          - {label: Description, name: description, widget: string}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: Testimonials, name: testimonialsabout, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: "Team Title", name: "teamtitle", widget: string, required: false}
          - {label: "Team Image New", name: "featuredimage", widget: image, required: false}
          - {label: Team Description, name: description, widget: string}
      - file: "src/pages/executive-team/index.md"
        label: "Executive Team"
        name: "executive-team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "executive-team"}
          - {label: "Title", name: "title", widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/core-team/index.md"
        label: "Core Team"
        name: "core-team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "core-team"}
          - {label: "Title", name: "title", widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          